services:
  - type: web
    name: prysm-backend
    plan: free
    env: node
    rootDir: backend
    buildCommand: npm install
    startCommand: node src/index.js
    envVars:
      - key: PORT
        value: 5000
      - key: NODE_ENV
        value: production
      - key: FRONTEND_URL
        sync: false
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        sync: false
